# Generated by Django 4.1.2 on 2022-11-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('bio', models.CharField(max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Developing something amazing'), (1, 'This could be interesting....'), (2, 'Man, life is so good'), (3, 'There is nothing quite like a good friend'), (4, 'Take a look around you, everything is awesome'), (5, 'What is the point of all of this')], default=0)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
